spring:
  application:
    name: bytecurto
  datasource:
    url: jdbc:postgresql://localhost:8432/bytecurto
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
