spring:
  application:
    name: bytecurto

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    root: INFO
    com.bryangabriel.bytecurto: INFO
    org.springframework: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %clr(%-5level){style} %clr(%logger{36}){cyan} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/app-bytecurto.log

  logback:
    rollingpolicy:
      file-name-pattern: "logs/archived/app-bytecurto-%d{yyyy-MM-dd}.%i.log"
      max-history: 30
      max-file-size: 10MB
      total-size-cap: 500MB

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:8432/bytecurto}
    username: ${DB_USER:${POSTGRES_USER}}
    password: ${DB_PASSWORD:${POSTGRES_PASSWORD}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  security:
    token:
      public-key: file:./certs/public_key.pem
      private-key: file:./certs/private_key.pem

logging:
  level:
    com.bryangabriel.bytecurto: DEBUG
    org.hibernate.SQL: ERROR

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  security:
    token:
      public-key: ${JWT_PUBLIC_KEY}
      private-key: ${JWT_PRIVATE_KEY}

server:
  port: ${PORT:8080}

app:
  base-url: "https://bytecurto-frontend.vercel.app"

logging:
  level:
    root: INFO
    com.bryangabriel.bytecurto: INFO
    org.springframework: WARN
    org.hibernate.SQL: OFF

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false
