ALTER TABLE users
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE links
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;