ALTER TABLE users
ADD COLUMN created_At DEFAULT TIMESTAMP CURRENT_TIMESTAMP,
ADD COLUMN update_At DEFAULT TIMESTAMP CURRENT_TIMESTAMP;

ALTER TABLE links
ADD COLUMN created_At DEFAULT TIMESTAMP CURRENT_TIMESTAMP,
ADD COLUMN update_At DEFAULT TIMESTAMP CURRENT_TIMESTAMP;